package com.spotinder.backend.spotify.service;

import com.spotinder.backend.spotify.client.SpotifyClient;
import com.spotinder.backend.spotify.dto.*;
import com.spotinder.backend.spotify.dto.playlist.AddTracksRequest;
import com.spotinder.backend.spotify.dto.playlist.CreatePlaylistRequest;
import com.spotinder.backend.spotify.dto.playlist.CreatePlaylistResponse;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestClient;

import java.util.List;

@Service
public class SpotifyService {


    private final SpotifyTokenService spotifyTokenService;
    private final SpotifyClient spotifyClient;
    private final RestClient restClient;

    public SpotifyService(SpotifyTokenService spotifyTokenService, SpotifyClient spotifyClient) {
        this.spotifyTokenService = spotifyTokenService;
        this.spotifyClient = spotifyClient;
        this.restClient = RestClient.create();

    }

    public List<SpotifyTrackResponse> getRecommendations() {

        return spotifyClient.getRecommendations();

    }

    public List<SpotifyTrackResponse> getTopTracks() {

        String accessToken = spotifyTokenService.getAccessToken();


        SpotifyTopTracksResponse response =
                restClient.get()
                        .uri("https://api.spotify.com/v1/me/top/tracks")
                        .header("Authorization", "Bearer " + accessToken)
                        .retrieve()
                        .body(SpotifyTopTracksResponse.class);

        if (response == null || response.items() == null) {
            return List.of();
        }

        return response.items()
                .stream()
                .map(track -> new SpotifyTrackResponse(

                        track.id(),
                        track.name(),
                        track.artists().isEmpty()
                                ? "Unknown Artist"
                                : track.artists().get(0).name(),
                        track.album().images().isEmpty()
                                ? null
                                : track.album().images().get(0).url()

                ))
                .toList();
    }

    public List<SpotifyTrackResponse> getRecentlyPlayed() {

        String accessToken = spotifyTokenService.getAccessToken();

        SpotifyRecentlyPlayedResponse response =
                restClient.get()
                        .uri("https://api.spotify.com/v1/me/player/recently-played")
                        .header("Authorization", "Bearer " + accessToken)
                        .retrieve()
                        .body(SpotifyRecentlyPlayedResponse.class);

        if (response == null || response.items() == null) {
            return List.of();
        }

        return response.items()
                .stream()
                .map(item -> {

                    SpotifyTrack track = item.track();

                    return new SpotifyTrackResponse(

                            track.id(),
                            track.name(),
                            track.artists().isEmpty()
                                    ? "Unknown Artist"
                                    : track.artists().get(0).name(),
                            track.album().images().isEmpty()
                                    ? null
                                    : track.album().images().get(0).url()

                    );

                })
                .toList();

    }

    public String getCurrentUserId() {

        String accessToken = spotifyTokenService.getAccessToken();

        System.out.println("Bearer :" + accessToken);

        SpotifyUserProfile user = restClient.get()
                .uri("https://api.spotify.com/v1/me")
                .header("Authorization", "Bearer " + accessToken)
                .retrieve()
                .body(SpotifyUserProfile.class);

        if (user == null) {
            throw new RuntimeException("Unable to retrieve Spotify profile.");
        }

        return user.id();

    }

    public CreatePlaylistResponse createPlaylist(String userId, String name) {

        String accessToken = spotifyTokenService.getAccessToken();

        System.out.println("Access Token: " + accessToken);

        System.out.println("User ID: " + userId);

        CreatePlaylistRequest request = new CreatePlaylistRequest(
                name,
                "Generated by Spotinder",
                false
        );

        CreatePlaylistResponse response = restClient.post()
                .uri("https://api.spotify.com/v1/users/{userId}/playlists", userId)
                .header("Authorization", "Bearer " + accessToken)
                .body(request)
                .retrieve()
                .body(CreatePlaylistResponse.class);

        if (response == null) {
            throw new RuntimeException("Failed to create playlist.");
        }

        return response;
    }


    public void addTracksToPlaylist(

            String playlistId,
            List<String> trackIds

    ) {

        String accessToken = spotifyTokenService.getAccessToken();

        List<String> uris = trackIds.stream()
                .map(id -> "spotify:track:" + id)
                .toList();

        AddTracksRequest request = new AddTracksRequest(uris);

        restClient.post()
                .uri("https://api.spotify.com/v1/playlists/{playlistId}/tracks", playlistId)
                .header("Authorization", "Bearer " + accessToken)
                .body(request)
                .retrieve()
                .toBodilessEntity();
    }



}