spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5433/spotinder
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true


spotify.client-id=e147e1a4be324dd5b64ebafc6bc745ef
spotify.client-secret=b6fdea0c930f4100a7988ed3ef351ac3
spotify.redirect-uri=http://127.0.0.1:8080/login/oauth2/code/spotify
spotify.api-url=https://api.spotify.com/v1


spring.security.oauth2.client.registration.spotify.client-id=e147e1a4be324dd5b64ebafc6bc745ef
spring.security.oauth2.client.registration.spotify.client-secret=b6fdea0c930f4100a7988ed3ef351ac3
spring.security.oauth2.client.registration.spotify.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.spotify.redirect-uri=http://127.0.0.1:8080/login/oauth2/code/spotify
spring.security.oauth2.client.registration.spotify.scope=user-read-email,user-read-private,user-top-read,user-read-recently-played,playlist-modify-public,playlist-modify-private

spring.security.oauth2.client.provider.spotify.authorization-uri=https://accounts.spotify.com/authorize
spring.security.oauth2.client.provider.spotify.token-uri=https://accounts.spotify.com/api/token
spring.security.oauth2.client.provider.spotify.user-info-uri=https://api.spotify.com/v1/me
spring.security.oauth2.client.provider.spotify.user-name-attribute=id